### ISSUE TITLE
[book-2] - Create Post(s) - Validation

### ISSUE THREAD

**Issue by Vojkan94** [Vojkan94/BIT-BOOK#15]
- For text post only text
- For video post only youtube links are valid input
- Links should be appropriately formatted to be “embedded”
- Input: https://www.youtube.com/watch?v=gAJkikwPtBs
- Output: https://www.youtube.com/embed/gAJkikwPtBs  
- For image only image urls are valid input

**Comment by doskovicmilos** [comment]
🚀
